networks:
  cloud-net:
    name: cloud-net

services:
  web-frontend-server:
    # build: ./web-frontend-server
    image: nhanhuutran007/myminicloud-web:latest
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  application-backend-server:
    # build: ./application-backend-server
    image: nhanhuutran007/myminicloud-app:latest
    networks:
      - cloud-net
    environment:
      OIDC_ISSUER: "http://authentication-identity-server:8080/realms/TranHuuNhan_52300235"
      OIDC_AUDIENCE: "account"
      OIDC_INTROSPECT_URL: "http://localhost:8081/realms/TranHuuNhan_52300235/protocol/openid-connect/token/introspect"
      OIDC_INTROSPECT_CLIENT_ID: "backend-introspect"
      OIDC_INTROSPECT_CLIENT_SECRET: "xoVeDIeu2SPJ9Lj8y4AY36sVMNvEKbtO"
      # Chọn chế độ xác thực:
      OIDC_MODE: "introspect"
      # Kết nối MariaDB
      DB_HOST: "relational-database-server"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "studentdb"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  relational-database-server:
    image: mariadb:11
    container_name: relational-database-server
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minicloud
    volumes:
      - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: ["start-dev", "--proxy-headers", "xforwarded", "--hostname-strict=false"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      JAVA_OPTS: "-Xms256m -Xmx768m"
    volumes:
      - keycloak-data:/opt/keycloak/data
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - cloud-net
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  internal-dns-server:
    build: ./internal-dns-server
    container_name: internal-dns-server
    networks:
      - cloud-net
    restart: unless-stopped
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M


  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    ports:
      - "9100:9100"
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - cloud-net
    restart: unless-stopped

  api-gateway-proxy-server:
    image: nginx:alpine
    container_name: api-gateway-proxy-server
    depends_on:
      - web-frontend-server
      - application-backend-server
      - authentication-identity-server
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cloud-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  mariadb-data:
    name: mariadb-data
  keycloak-data:
    name: keycloak-data
  grafana-data:
    name: grafana-data
  prometheus-data:
    name: prometheus-data
